export const environment = {
  production: true,
  appUrl: 'http://multiple_service.local',
  appKey: 'secret',
  jwtTtl: '3600000000',
  appEnv: 'local',
  dbLog: true,
  migrationsRun: true,
  dbConnection: 'mysql',
  dbHost: 'localhost',
  dbPort: '3306',
  dbName: 'multiple_service',
  dbUser: 'mwx',
  dbPass: '0111mvtT',
}
